### ISSUE TITLE
frontend: issues

### ISSUE THREAD

**Issue by chrzrdx** [suryakumarigoluguri/edyst-s19-pokemon-battle-scene#1]
Improve the information boxes (make them rounded, add more info, align name/level/hp properly)

Make the characters bigger

use a smaller background

**Comment by chrzrdx** [comment]
center the arena (main image) on the page; both vertically and horizontally

**Comment by suryakumarigoluguri** [comment]
jemima helped me,by pull request
so the problem is solved
